### ISSUE TITLE
View class - simplify with method

### ISSUE THREAD

**Issue by dr-matt-smith** [Year4-Games-Development/Team1-Game2#16]
this code appears several times:
`(new Vector3Int(-x + width / 2, -y + height / 2, 0)`

so I think you should write a method (with good name /. comment) to:

- make it clear what it does
- get rid of duplicated code (so if function changes, it can be changed in one place only)

**Comment by zantcho** [comment]
the class is commented and simplified
lot of variable change to a more semantic name

a private method TileCoordinates  has been created
